### PR TITLE
4 write test

### PR DESCRIPTION
**Pull request by samdansk2**

### CODE REVIEW

**Comment by samdansk2** [comment]
@vamseeachanta 

There are some checks which have failed sir , 
Need to look up the workflow file 👍

**Comment by samdansk2** [comment]
It is unable to find the test file which is located in tests directory , 
Import Error : Failed importing tests module

**Comment by vamseeachanta** [comment]
@samdansk2 Are the same tests running on your computer locally first. I assume they are.

**Comment by vamseeachanta** [comment]
os is not a python library. It is a default module that comes directly from python

https://github.com/samdansk2/librarytemplate/actions/runs/8243729035/job/22544799609?pr=6
image

**Comment by samdansk2** [comment]
> @samdansk2 Are the same tests running on your computer locally first. I assume they are.

Yes sir , all tests have passed locally in my system

**Comment by samdansk2** [comment]
> os is not a python library. It is a default module that comes directly from python
> 
> https://github.com/samdansk2/librarytemplate/actions/runs/8243729035/job/22544799609?pr=6 image

Yes sir, removed os from requirements file

**Comment by samdansk2** [comment]
@vamseeachanta 
hello sir , searched a lot about  unittest discovery error ,  but no proper solution found

so i go with **pytest**

**Comment by samdansk2** [comment]
@vamseeachanta 
What's  the next step, sir? We need to convert it to a library!

**Comment by samdansk2** [comment]
@vamseeachanta 

As you said , i prepared the notes about of fstrings 
fstrings :  https://github.com/samdansk2/Ace-Task-1/blob/main/Fstrings

**Comment by vamseeachanta** [comment]
https://github.com/vamseeachanta/py_package/blob/master/README.md

**Comment by vamseeachanta** [comment]
https://github.com/vamseeachanta/py_package/blob/improvements/README.md

Play with TestPyPI before uploading pypi.

**Pull request merged**
