### PR TITLE
folder structure

### PR DESCRIPTION
**Pull request by vamseeachanta**

### CODE REVIEW

**Comment by vamseeachanta** [comment]
@samdansk2 , 
Looks like you accomplished step 2. Now on to step 3 of creating new branch "3_sample_calculation"

On a side note, you should have put this read yaml code in "2_read_yml" branch rather than "folder_structure" branch.  This way we follow the organization proposed below.  Note we added folder_structure as first one.
https://github.com/vamseeachanta/assetutilities/blob/2024/docs/_public_library.puml
CC: @samdansk2

**Comment by samdansk2** [comment]
@vamseeachanta 
Hello sir, Done with the calculation and
Also created a test for this calculation 👍
Please see it sir.

**Comment by samdansk2** [comment]
@vamseeachanta 

Yaml :
https://github.com/samdansk2/Ace-Task-1/blob/main/YAML%20NOTES

**Comment by vamseeachanta** [comment]
We will sit together and improve this yaml notes.

**Pull request closed without merging**
